"""
Django settings for FURFEASTCO project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-u%=m_jym@7l@45gval389byel^zg#%7pian(h3p0j68y90%+q+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']

# CSRF settings for deployment
CSRF_TRUSTED_ORIGINS = [
    'https://taj8z613n2jd7-furfeastco--8000.prod2.defang.dev',
    'https://*.defang.dev',
    'https://*.australia-southeast2.run.app',
    'https://furfeastco-168900719564.australia-southeast2.run.app',
]
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'

# --- Google Cloud Storage Settings ---
GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME')

if GS_BUCKET_NAME:  # Only apply GCS settings if the bucket name is defined
    # Static files (CSS, JavaScript, images)
    STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'
    
    # Media files (user-uploaded content)
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'
    
    # Set default permissions for uploaded files to be publicly readable
    GS_DEFAULT_ACL = 'publicRead'
    
    # Update STORAGES configuration for Django 4.2+
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
    }
else:
    # Fallback to existing Supabase storage
    STORAGES = {
        "default": {
            "BACKEND": "furfeast.storage.SupabaseStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
# --- End Google Cloud Storage Settings ---

# Static files settings for production
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'furfeast' / 'static',
]

# Media files settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Supabase Storage Configuration
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://wivxshghrwmgxstaowjl.supabase.co')
SUPABASE_KEY = os.getenv('SUPABASE_SERVICE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpdnhzaGdocndtZ3hzdGFvd2psIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzE4NDU2MSwiZXhwIjoyMDgyNzYwNTYxfQ.F62rm6cFzBccK477VyqFVSjXCzCeW4ZmsTQ1LJYrOvY')
SUPABASE_BUCKET_NAME = 'FurfeastCo.'

# Use Supabase storage for file uploads
DEFAULT_FILE_STORAGE = 'furfeast.storage.SupabaseStorage'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'furfeast',
]

MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'FURFEASTCO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'furfeast.context_processors.promo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'FURFEASTCO.wsgi.application'
ASGI_APPLICATION = 'FURFEASTCO.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': 'require',  # Supabase requires SSL
        },
        'CONN_MAX_AGE': 0,  # Disable persistent connections
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.AttributeSimilarityValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'furfeast' / 'static',
]

# Static file optimization
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Cache static files for 1 year and compress them
WHITENOISE_MAX_AGE = 31536000
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Additional performance optimizations
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Additional performance optimizations
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Cache configuration for pages
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'furfeast'

# Media files settings are handled by STORAGES['default']



# Legacy settings (kept for compatibility or reference, but STORAGES takes precedence)
# DEFAULT_FILE_STORAGE = 'furfeast.storage.SupabaseStorage'

# Supabase Storage Configuration
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://wivxshghrwmgxstaowjl.supabase.co')
SUPABASE_KEY = os.getenv('SUPABASE_SERVICE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpdnhzaGdocndtZ3hzdGFvd2psIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzE4NDU2MSwiZXhwIjoyMDgyNzYwNTYxfQ.F62rm6cFzBccK477VyqFVSjXCzCeW4ZmsTQ1LJYrOvY')
SUPABASE_BUCKET_NAME = 'FurfeastCo.'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Optimized Caching Configuration for 2-second loading
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'furfeast-cache',
        'TIMEOUT': 900,  # 15 minutes for better performance
        'OPTIONS': {
            'MAX_ENTRIES': 500,  # Increased for better caching
        }
    }
}

# Database Connection Optimization
DATABASE_CONNECTION_POOLING = True
CONN_MAX_AGE = 600  # 10 minutes

# Template Caching
TEMPLATE_CACHE_TIMEOUT = 3600  # 1 hour

# Session Optimization
SESSION_CACHE_ALIAS = 'default'
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_COOKIE_AGE = 86400  # 24 hours

# Auth Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'cofurfeast@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'omylzdzofbxymrxv')

# Email Verification Settings
EMAIL_VERIFICATION_REQUIRED = True
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# PayPal Configuration
PAYPAL_CLIENT_ID = 'AXDh7dyyix7N1dDlS8jKhPATLOZZz3sspEpZa683c6_1vo4otgt62aebiUoZy_JSmvSqDU1kJ056Em0T'
PAYPAL_CLIENT_SECRET = 'EPY4XVLrZB6yJqillbqjDfipk06rfa5n6OhpXCNkMEURVSOtQp-VWpA3nKWXR11-A4oJ8uCdzY63E8OC'
PAYPAL_MODE = 'sandbox'  # 'sandbox' for testing, 'live' for production
