# Generated by Django 5.1.3 on 2025-12-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dog-food', 'Dog Food'), ('cat-food', 'Cat Food'), ('accessories', 'Accessories')], default='dog-food', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
