# Generated by Django 5.1.3 on 2025-12-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furfeast.product'),
        ),
    ]
