# Generated by Django 5.1.3 on 2025-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0004_flashsale_title_product_is_out_of_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_bar_active', models.BooleanField(default=True)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('promo_code_text', models.CharField(default='FURFEAST10', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
