# Generated by Django 5.1.3 on 2025-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum order for free shipping', max_digits=10),
        ),
    ]
