# Generated by Django 5.1.3 on 2025-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0006_delete_siteconfiguration_promocode_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_position_y',
            field=models.IntegerField(default=0),
        ),
    ]
