# Generated by Django 5.1.3 on 2025-12-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0007_blog_image_position_x_blog_image_position_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_position_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_position_y',
            field=models.FloatField(default=50.0),
        ),
    ]
