# Generated by Django 5.1.3 on 2025-12-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0010_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About FurFeast', max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
