# Generated by Django 5.1.3 on 2025-12-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0011_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='happy_pet_parents_count',
            field=models.CharField(default='10k+', max_length=20),
        ),
    ]
