# Generated by Django 5.1.3 on 2025-12-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0012_aboutus_happy_pet_parents_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
