# Generated by Django 5.1.3 on 2025-12-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0013_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('video', models.FileField(blank=True, null=True, upload_to='campaigns/videos/')),
                ('sent_to_registered', models.BooleanField(default=False)),
                ('sent_to_customers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
