# Generated by Django 5.1.3 on 2025-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0014_massemailcampaign_userprofile_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massemailcampaign',
            name='recipients_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BusinessTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('week', 'This Week'), ('month', 'This Month'), ('year', 'This Year')], max_length=10)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField(default=2024)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('period', 'year', 'month', 'week')},
            },
        ),
    ]
