# Generated by Django 5.1.3 on 2025-12-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0015_massemailcampaign_recipients_count_businesstarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price (will show as strikethrough)', max_digits=10, null=True),
        ),
    ]
