# Generated by Django 5.1.3 on 2025-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0016_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='category',
            field=models.CharField(blank=True, choices=[('dog-food', 'Dog Food'), ('cat-food', 'Cat Food'), ('accessories', 'Accessories')], help_text='Category for flash sale (optional)', max_length=50, null=True),
        ),
    ]
