# Generated by Django 5.1.3 on 2026-01-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0017_flashsale_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hero/')),
                ('headline', models.CharField(max_length=200)),
                ('subheadline', models.CharField(max_length=300)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_link', models.CharField(default='/shop/', max_length=200)),
                ('align', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
