# Generated by Django 5.1.3 on 2026-01-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0018_heroimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='massemailcampaign',
            name='sent_to_furfeast_family',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FurFeastFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_category', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], max_length=20)),
                ('pet_age', models.CharField(max_length=50)),
                ('favourite_food', models.CharField(max_length=200)),
                ('additional_description', models.TextField(blank=True)),
                ('receive_expert_emails', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
