# Generated by Django 5.1.3 on 2026-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0020_pendingregistration_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='text_position_y',
            field=models.IntegerField(default=50, help_text='Text vertical position (0-100)'),
        ),
    ]
