# Generated by Django 5.1.3 on 2026-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0021_heroimage_text_position_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='text_position_x',
            field=models.IntegerField(default=10, help_text='Text horizontal position (0-100)'),
        ),
    ]
