# Generated by Django 5.1.3 on 2026-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0026_order_payment_method_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal')], default='paypal', max_length=20),
        ),
    ]
