# Generated by Django 5.1.3 on 2026-01-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0029_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='desktop_image',
            field=models.ImageField(blank=True, help_text='Landscape image for desktop (1920x800 recommended)', null=True, upload_to='hero/desktop/'),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Portrait/square image for mobile (800x800 recommended)', null=True, upload_to='hero/mobile/'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(help_text='Legacy field - use desktop_image instead', upload_to='hero/'),
        ),
    ]
