# Generated by Django 5.1.3 on 2026-01-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0030_heroimage_desktop_image_heroimage_mobile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer_name',
            field=models.CharField(blank=True, help_text='Display name for the writer (optional, defaults to admin username)', max_length=100),
        ),
    ]
