# Generated by Django 5.1.3 on 2026-01-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0032_customermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
