# Generated by Django 5.1.3 on 2026-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furfeast', '0033_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('message', 'Message'), ('order', 'Order')], default='general', max_length=50),
        ),
    ]
