# Generated by Django 4.2.7 on 2026-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furfeast", "0036_chatbotintent_chatbotsession_chatbotconversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingregistration",
            name="verification_token",
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="otp",
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
